### ISSUE TITLE
Potential Database Change

### ISSUE THREAD

**Issue by IMBCIT** [ASU-CodeDevils/codedevils.org#1]
We should look at potentially changing from the default SQLite to PostgreSQL. This is probably not necessary but PostgreSQL is a good database for people to learn if they do not have exposure to it.

**Comment by reharri7** [comment]
I agree

**Comment by IMBCIT** [comment]
If we decide to use PostgreSQL, PlanetScale will not work as that is MySQL based and we will have to run something else. It is not really a huge issue but we can test out both options and see how it goes.

#5
