### ISSUE TITLE
Investigate Website Perf Issues (especially on mobile experience)

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#25]
Chrome Lighthouse reports a score of 33 which is well below acceptable, especially for a website that is serving static content with essentially no complex logic.

<img width="520" alt="Screen Shot 2023-05-02 at 2 59 33 PM" src="https://user-images.githubusercontent.com/34381646/235797636-bbcad66f-1401-4e50-965d-e09aa795d4f8.png">

**Comment by fernandonevarez** [comment]
The website performance issues were addressed during development and this is no longer an issue. 

The current production website performance stats can be found [here](https://pagespeed.web.dev/analysis/https-codedevils-a6z80m059-code-devils-vercel-app/eqkafvb3k0?form_factor=desktop).
