### ISSUE TITLE
Remove all unnecessary line breaks

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#27]
Line breaks `<br />` are meant for breaks in paragraphs of text and should never be used for formatting / aligning context. Prefer margin and proper CSS classes instead.

Line Break MDN Docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br
Margin MDN Docs: https://developer.mozilla.org/en-US/docs/Web/CSS/margin

<img width="1287" alt="Screen Shot 2023-05-02 at 3 04 42 PM" src="https://user-images.githubusercontent.com/34381646/235798115-134b4441-0525-424c-9143-8c0de1780cfd.png">

**Comment by fernandonevarez** [comment]
I used the line breaks for testing, mainly to make sure the navbar was changing styles based on the `isUserScrolling` useState in `navbar.tsx`.

**Comment by fernandonevarez** [comment]
But I'll make sure to remove them.

**Comment by fernandonevarez** [comment]
alright, finish removing them.
