### ISSUE TITLE
Translation icon on desktop is blank

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#28]
<img width="306" alt="Screen Shot 2023-05-02 at 3 21 28 PM" src="https://user-images.githubusercontent.com/34381646/235798351-1aed355e-99f7-4f82-aa2f-85dc16e99bb5.png">

**Comment by fernandonevarez** [comment]
Fixed this issue, it was related to our dark mode theme colors we were having.
