### ISSUE TITLE
Conform header heights so transitions are smoother

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#30]
The header heights on every page are different and therefore the transitions between pages are janky. The text transitions look nice so if the heights are all the same it will look much better.

e.g. below heights are 370px vs 435px
<img width="360" alt="Screen Shot 2023-05-02 at 3 23 57 PM" src="https://user-images.githubusercontent.com/34381646/235798715-2caf4db5-8ce3-4236-a01a-12f43d3a2175.png">
<img width="359" alt="Screen Shot 2023-05-02 at 3 24 04 PM" src="https://user-images.githubusercontent.com/34381646/235798720-9585bff1-4b63-4224-9ed9-caff323643f0.png">

**Comment by fernandonevarez** [comment]
Alright fix this
