### ISSUE TITLE
Revert to the older version while the new version is under construction

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#31]
Not required - but it seems weird to have this banner be displayed with an unfinished v2 site instead of displaying the finished v1 website then cutting over to this v2 rewrite after it is finished?

<img width="729" alt="Screen Shot 2023-05-02 at 3 26 13 PM" src="https://user-images.githubusercontent.com/34381646/235799014-17836fd6-be88-4522-b4ac-3e7c4e59e001.png">

**Comment by fernandonevarez** [comment]
The website was finished and published; this is no longer a concern.
