### ISSUE TITLE
No favicon displayed on Safari mobile

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#32]
Tested on iPhone 14 Pro - iOS  16.4.1

Current experience:
<img width="200" src="https://user-images.githubusercontent.com/34381646/235799490-50b4d9d3-2b60-49dc-ab74-9f4e25d303c6.jpg">

Working example:
<img width="200" src="https://user-images.githubusercontent.com/34381646/235799872-8a2bce3a-e933-4c39-bfbf-5f205e142341.jpg">

**Comment by fernandonevarez** [comment]
fixed this issue
