### ISSUE TITLE
Fix mobile/desktop identifier in AppContext

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#33]
Currently we just read the `innerWidth`: https://github.com/ASU-CodeDevils/codedevils/blob/56a77d9929c2133716ea311af891197aab129987/src/contexts/AppContext.jsx#L13

According to MDN this is a "Crude way to check that the screen is at least 1024x768": https://developer.mozilla.org/en-US/docs/Web/API/Screen/width

We can check the `navigator.userAgent` and we can also detect if the device has a touch screen. You can fallback to a screen width reading if necessary.

**Comment by fernandonevarez** [comment]
good to know, but we aren't using the react context API anymore.
