### ISSUE TITLE
Focus on mobile first

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#34]
According to a study in 2019 (and it has only grown since) ~63% or US internet traffic is mobile: https://research.com/software/mobile-vs-desktop-usage

It looks like we default to desktop in appContext and also are prioritizing desktop issues over mobile.
https://github.com/ASU-CodeDevils/codedevils/blob/56a77d9929c2133716ea311af891197aab129987/src/contexts/AppContext.jsx#L7

We should always focus on mobile first since that will be the large majority of usage on the site.

**Comment by fernandonevarez** [comment]
Yeah, that's true. I just default to false values on Boolean states. But I'm going to be refactoring the whole navbar to use CSS media queries instead, as that's best practice.
