### ISSUE TITLE
Stop logging to console on prod experience

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#35]
We currently expose logging on the console - we should have a `isProd` flag that is enabled on the prod hosted website. Logging should only be used when testing local changes.

<img width="595" alt="Screen Shot 2023-05-02 at 3 51 26 PM" src="https://user-images.githubusercontent.com/34381646/235802323-50507223-336f-49a5-831a-fab46e1e5d0b.png">

**Comment by fernandonevarez** [comment]
oops, I'll work on fixing that. Also, I work on adding that flag in the production build.
