### ISSUE TITLE
Consider using CSS-in-JS or Tailwind

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#36]
There are a lot of CSS-in-JS libraries that support React/Next out of the box. One in particular is Styled JSX: https://github.com/andreipfeiffer/css-in-js/blob/main/README.md#styled-jsx

This helps scope CSS to components and reduce the weight of looking for style sheet pairs for each class.

Right now our codebase has SASS files for each component that can be hard to reason about.
Here is one that is nested five dirs deep:
https://github.com/ASU-CodeDevils/codedevils/blob/main/src/styles/components/page_layout/footers/desktop.module.scss

**Comment by fernandonevarez** [comment]
okay I did 💋
