### ISSUE TITLE
Clean up unused files

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#37]
Why do we have files like [tailwind.config.cjs](https://github.com/ASU-CodeDevils/codedevils/blob/main/tailwind.config.cjs) if we're not using tailwind? There seems to be a lot of these boilerplate files that are completely unused and adding bloat.

**Comment by IMBCIT** [comment]
We are supposed to be using tailwind

**Comment by reharri7** [comment]
Be a 10xer and delete the bloat

**Comment by fernandonevarez** [comment]
alright bet

**Comment by 0xfr4nkie** [comment]
Are we no longer using Tailwind?

**Comment by jsontm** [comment]
> Are we no longer using Tailwind?

Looking at the project there is a dedicated SASS style sheet for every component/page. No signs of Tailwind being used currently.

**Comment by jsontm** [comment]
Related issue #36

**Comment by fernandonevarez** [comment]
i'll get rid of the tailwind file

**Comment by fernandonevarez** [comment]
> We are supposed to be using tailwind
fine, I'll work on relearning it.
