### ISSUE TITLE
Refactor Navbar.tsx

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#40]
**There are 31 ternary conditions in this one file.** This may be a record.

`Navbar.tsx` is over 400 LoC long. It includes a separate mobile and desktop navbar with custom impls for each of them all in the same file. This goes against all the design principles of React. These should be separate components if they are dissimilar enough to warrant so and you can build up HoC (higher order components) out of multiple sub-components. The current implementation is unreadable.

https://github.com/ASU-CodeDevils/codedevils/blob/main/src/components/page_layout/Navbar.tsx

**Comment by reharri7** [comment]
🥇

**Comment by fernandonevarez** [comment]
Don't even get me started on how much I hate myself for this navbar component design. I promise ik what I am doing, but yeah I just need to set time to actually work on fixing my horrible code and that's just putting it lightly.

**Comment by reharri7** [comment]
👀

**Comment by fernandonevarez** [comment]
okay I finished doing this, but I'll leave this issue open.

**Comment by fernandonevarez** [comment]
The issue was eliminated, and this is no longer a concern.
