### ISSUE TITLE
Upgrade to Next.js 14

### ISSUE THREAD

**Issue by IMBCIT** [ASU-CodeDevils/codedevils.org#48]
Next.js 13 has now been prod for quite a while now. 

We should move to this while the application is still pretty fresh. There will be a slight learning curve particularly in server and client components but the transition shouldn't be too hard.

Here is a link to the docs [Next.js 13](https://nextjs.org/docs).

**Comment by fernandonevarez** [comment]
As Version 14 of Next.js is out, we will update our codebase to that.
