### ISSUE TITLE
Update sitemap

### ISSUE THREAD

**Issue by 0xfr4nkie** [ASU-CodeDevils/codedevils.org#76]
Update the following to reflect the codedevils.org domain:

- [app/sitemap.ts](https://github.com/ASU-CodeDevils/codedevils.org/blob/main/app/sitemap.ts)
- [app/robots.ts](https://github.com/ASU-CodeDevils/codedevils.org/blob/84eb38793af6f0282d1c207745b77887dd2ab68e/app/robots.ts)
- [utils/metadata.ts](https://github.com/ASU-CodeDevils/codedevils.org/blob/84eb38793af6f0282d1c207745b77887dd2ab68e/utils/metadata.ts)

**Comment by frankjlin16** [comment]
Update [robots.ts](https://github.com/ASU-CodeDevils/codedevils.org/blob/84eb38793af6f0282d1c207745b77887dd2ab68e/app/robots.ts) as well.
