### ISSUE TITLE
Fix gaps in `codedevils-logo.svg`

### ISSUE THREAD

**Issue by fernandonevarez** [ASU-CodeDevils/codedevils.org#81]
### Description of the bug:
The `codedevils-logo.svg` currently has gaps within the SVG file, and the logo does not occupy the full size of the SVG canvas. This results in extra padding or white space around the logo, affecting its display quality across the site.

Although the images provided in this issue show the mobile view, the issue persists across other views as well.

**Expected behavior:**  
The logo should take up the full SVG area without any unnecessary margins or gaps.

### Steps To Reproduce:
1. Go to [https://www.codedevils.org](https://www.codedevils.org)
2. Scroll down to the footer or inspect the navbar logo
3. Inspect the logo's dimensions and padding
4. Notice the gaps and extra padding around the SVG logo

### Additional Information:
![kjnkjn](https://github.com/user-attachments/assets/4c4c5d9a-36eb-4641-b4d0-dd8df9f6480a)  
![IMG_9241](https://github.com/user-attachments/assets/22094a57-74fa-4ea9-98d2-c0ff968d66eb)

**Comment by Mohitpanjikar** [comment]
can i work on this issue ?

**Comment by fernandonevarez** [comment]
Hello @Mohitpanjikar, Yes, you can. Just make sure to read our [contributing docs](https://github.com/ASU-CodeDevils/codedevils.org/blob/main/.github/CONTRIBUTING.MD) and format your commit as [required](https://github.com/ASU-CodeDevils/codedevils.org/blob/main/README.md#contributing-code-style) when you submit your commits. If you have any problems, please don't hesitate to reach out to an officer or even to me.
