### ISSUE TITLE
Fix H2 alignment to be left-aligned on mobile view ONLY

### ISSUE THREAD

**Issue by fernandonevarez** [ASU-CodeDevils/codedevils.org#82]
### Description of the bug:
The H2 heading in the section "Our members are getting jobs and internships from top companies. We can help you too." is currently centered in the mobile view. For better mobile responsiveness, the text should be left-aligned to maintain consistency with the rest of the page design.

**Expected behavior:**  
The H2 heading should be left-aligned on mobile devices ONLY, DO NOT SET IT LEFT-ALIGNED for any other view.

### Steps To Reproduce:
1. Go to [https://www.codedevils.org](https://www.codedevils.org) on a mobile device or use the browser's developer tools to simulate a mobile view.
2. Scroll to the section with the H2 heading "Our members are getting jobs and internships from top companies. We can help you too."
3. Observe that the text is centered.

### Additional Information:
Here are screenshots showing the issue:

![kcmsmlcas](https://github.com/user-attachments/assets/1617dbed-3f36-4604-9dcb-622092c8da43)
)  
![usaiukjh](https://github.com/user-attachments/assets/96042cd6-bbeb-45cd-b9fb-491cd3029f83)
The text should be adjusted to be left-aligned on smaller screen sizes.

**Comment by Mohitpanjikar** [comment]
hey i want to work on this issue can i ?

**Comment by fernandonevarez** [comment]
Hello @Mohitpanjikar, Yes, you can. Just make sure to read our [contributing docs](https://github.com/ASU-CodeDevils/codedevils.org/blob/main/.github/CONTRIBUTING.MD) and format your commit as [required](https://github.com/ASU-CodeDevils/codedevils.org/blob/main/README.md#contributing-code-style) when you submit your commits. If you have any problems, please don't hesitate to reach out to an officer or even to me.

**Comment by PitaFLAME** [comment]
Go for it @Mohitpanjikar!  Feel free to reach out to any of us on the discord if you have any issues or questions.
