### ISSUE TITLE
Project Page Git Repo Links

### ISSUE THREAD

**Issue by PitaFLAME** [ASU-CodeDevils/codedevils.org#89]
Every project page needs a link to the git repo.  Below is an image for positioning/size approximation.  Data will need to be stored in content.tsx.

![image_2024-10-09_182554104](https://github.com/user-attachments/assets/a606f083-017d-4cb9-9b5b-acf0df17134f)

_25 points_

**Comment by YB-Yottabyte** [comment]
I will work on this issue

**Comment by PitaFLAME** [comment]
_Completed_

**Comment by PitaFLAME** [comment]
You worked hard on this.  I'm awarding another 10 points to the issue.
