### ISSUE TITLE
[DOCS]: Create Issue Templates

### ISSUE THREAD

**Issue by fernandonevarez** [ASU-CodeDevils/codedevils.org#99]
So that it's easier for contributors to create issues within the project, I recommend creating issue templates for the project.

the files should be created in `./.github/ISSUE_TEMPLATE/`

you can learn more about how to create them from Github's docs [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) or just look at some i have create before [here](https://github.com/fernandonevarez/lms/tree/main/.github/ISSUE_TEMPLATE)

**Comment by fernandonevarez** [comment]
Also, create a `config.yml` file with the content of `blank_issues_enabled: false` within the  `./.github/ISSUE_TEMPLATE/` route to ensure that no one can create an issue without following the templates, if you want to enforce their use.

**Comment by PitaFLAME** [comment]
Completed.

**Comment by fernandonevarez** [comment]
Oh @PitaFLAME, it seems that instead of making the templates, you created a file explaining what to do, which is totally fine as this is just a suggestion. However, I just wanted to point out something you might not be aware of: while you, by default, have permissions to add labels and other details to issues, “outside contributors” do not. This means that they can't add labels or other things when submitting issues as suggested [here](https://github.com/ASU-CodeDevils/codedevils.org/blob/main/.github/ISSUE_GUIDE.MD#template-and-requirements)

By actually creating the issue templates, you'll make it much easier for newcomers and outside  contributors to contribute to the project and ensure they provide all the necessary information that you and the leadership would want in the issues. You can read more about how to make them [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) as even if you don't want to add them to the project, it's something good to know later down the line when you get a SWE job.

Additionally, you can assign default labels and make things required to issues submitted by “outside contributors”, which would help streamline the process for everyone. Just something to consider, as these templates can be really helpful for those who are just getting started with GitHub.
